Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-07, with the labels that each got.

#175 fix: /lib for vendoring
  portkey_ai/version.py
  setup.cfg
Labels: auto:bug, size:XS

#177 1.7.0
  portkey_ai/version.py
Labels: size:XS

#182 Max Retries
  portkey_ai/api_resources/client.py
Labels: auto:enhancement, size:XS

#186 Allow token_logprobs and top_logprobs List to have Objects of None type
  portkey_ai/api_resources/types/complete_type.py
Labels: lgtm, auto:enhancement, size:XS

#178 chore: replace validators with field_validators to avoid deprecation …
  portkey_ai/api_resources/utils.py
Labels: auto:refactor, size:S

#184 virtual key script
  tests/virtual_keys_replacement.sh
Labels: size:XS

#188 hotfix: kwargs in extra_body
  portkey_ai/api_resources/apis/audio.py
  portkey_ai/api_resources/apis/batches.py
  portkey_ai/api_resources/apis/chat_complete.py
  portkey_ai/api_resources/apis/complete.py
  portkey_ai/api_resources/apis/embeddings.py
  portkey_ai/api_resources/apis/fine_tuning.py
  portkey_ai/api_resources/apis/images.py
  portkey_ai/api_resources/apis/main_files.py
  portkey_ai/api_resources/apis/models.py
  portkey_ai/api_resources/apis/moderations.py
Labels: auto:bug, size:L

#189 1.7.1rc1
  portkey_ai/version.py
Labels: size:XS

#190 1.7.1
  portkey_ai/version.py
Labels: size:XS

#192 Vertex Changes
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/types/chat_complete_type.py
Labels: auto:enhancement, size:M

#193 1.7.2
  portkey_ai/version.py
Labels: size:XS
