Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-03, with the labels that each got.

#94 Wrapper/suggestions
  portkey_ai/api_resources/apis/chat_complete.py
  portkey_ai/api_resources/apis/complete.py
  portkey_ai/api_resources/apis/embeddings.py
  portkey_ai/api_resources/apis/images.py
  portkey_ai/api_resources/apis/models.py
  tests/utils.py
Labels: size:L

#97 feat: release 1.2.0
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#98 chore: test case formatting
  tests/test_async_images.py
  tests/test_images.py
Labels: auto:improvement, size:S

#100 fix: build errors in test cases
  tests/test_assistants.py
  tests/test_async_chat_complete.py
  tests/test_async_complete.py
  tests/test_async_images.py
  tests/test_chat_complete.py
  tests/test_complete.py
  tests/test_images.py
  tests/test_threads.py
  tests/utils.py
Labels: auto:bug, size:M

#103 hotfix: openAI as dependency
  setup.cfg
Labels: lgtm, auto:bug, size:XS

#104 feat: release 1.2.1
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#96 Feat/render
  portkey_ai/api_resources/apis/generation.py
Labels: lgtm, auto:enhancement, size:M

#106 class Beta sub methods
  portkey_ai/api_resources/client.py
Labels: lgtm, auto:enhancement, size:XS

#107 feat: release 1.2.2
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#108 Add OpenAI SDK compliant blurb to readme
  README.md
Labels: lgtm, auto:documentation, size:XS
