Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-06, with the labels that each got.

#145 hotfix/ chat completion for azure
  portkey_ai/api_resources/types/chat_complete_type.py
Labels: size:S

#146 1.3.2
  portkey_ai/version.py
Labels: size:XS

#149 Latency Issue
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
Labels: auto:bug, size:S

#150 1.4.0
  portkey_ai/version.py
Labels: size:XS

#166 1.4.1
  portkey_ai/version.py
Labels: size:XS

#165 request_timeout header
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:S

#147 Add OpenAI SDK compatibility table
  README.md
Labels: lgtm, auto:documentation, size:M

#160 Release workflow
  .github/workflows/python-publish.yml
Labels: size:XS

#156 Script for virtual keys
  tests/configs/assistants/single_provider/single_provider.json
  tests/configs/assistants/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/assistants/single_with_basic_config/single_with_basic_config.json
  tests/configs/audio/single_provider/single_provider.json
  tests/configs/audio/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/audio/single_with_basic_config/single_with_basic_config.json
  tests/configs/chat_completions/loadbalance_and_fallback/anthropic_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/anyscale_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/azure_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/cohere_n_openai.json
  tests/configs/chat_completions/loadbalance_with_two_apikeys/loadbalance_with_two_apikeys.json
  tests/configs/chat_completions/single_provider/single_provider.json
  tests/configs/chat_completions/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/chat_completions/single_with_basic_config/single_with_basic_config.json
  tests/configs/completions/loadbalance_and_fallback/anthropic_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/anyscale_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/azure_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/cohere_n_openai.json
  tests/configs/completions/loadbalance_with_two_apikeys/loadbalance_with_two_apikeys.json
  tests/configs/completions/single_provider/single_provider.json
  tests/configs/completions/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/completions/single_with_basic_config/single_with_basic_config.json
  tests/configs/images/loadbalance_and_fallback/stability_n_openai.json
  tests/configs/images/loadbalance_with_two_apikeys/loadbalance_with_two_apikeys.json
  tests/configs/images/single_provider/single_provider.json
  tests/configs/images/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/images/single_with_basic_config/single_with_basic_config.json
  tests/configs/moderations/single_provider/single_provider.json
  tests/configs/moderations/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/moderations/single_with_basic_config/single_with_basic_config.json
  tests/configs/threads/single_provider/single_provider.json
  tests/configs/threads/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/threads/single_with_basic_config/single_with_basic_config.json
  tests/virtual_keys_replacement.sh
Labels: auto:enhancement, size:M

#127 langchain llamaindex callback handler
  Makefile
  portkey_ai/api_resources/apis/logger.py
  portkey_ai/llms/langchain/__init__.py
  portkey_ai/llms/langchain/portkey_langchain_callback.py
  portkey_ai/llms/llama_index/__init__.py
  portkey_ai/llms/llama_index/portkey_llama_callback.py
  setup.cfg
  tests/models.json
  tests/test_llm_langchain.py
  tests/test_llm_llamaindex.py
Labels: auto:enhancement, size:XL

#167 1.5.0
  portkey_ai/version.py
Labels: size:XS

#171 Hotfix: prompt rendor response type
  portkey_ai/api_resources/types/chat_complete_type.py
Labels: size:XS

#172 feat/release-1.5.1
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#174 1.6.0
  portkey_ai/version.py
Labels: auto:enhancement, size:XS
