Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-04, with the labels that each got.

#110 Fix/prompt response
  portkey_ai/api_resources/apis/generation.py
  portkey_ai/api_resources/common_types.py
  portkey_ai/api_resources/types/generation_type.py
  portkey_ai/api_resources/utils.py
Labels: lgtm, auto:bug, size:L

#111 feat: release 1.2.3
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#113 black package
  setup.cfg
Labels: lgtm, auto:bug, size:XS

#114 fix: private attribute changes for pydantic v1 compatibility
  portkey_ai/api_resources/types/assistant_type.py
  portkey_ai/api_resources/types/chat_complete_type.py
  portkey_ai/api_resources/types/complete_type.py
  portkey_ai/api_resources/types/embeddings_type.py
  portkey_ai/api_resources/types/generation_type.py
  portkey_ai/api_resources/types/image_type.py
  portkey_ai/api_resources/types/main_file_type.py
  portkey_ai/api_resources/types/models_type.py
  portkey_ai/api_resources/types/thread_message_type.py
  portkey_ai/api_resources/types/thread_run_type.py
  portkey_ai/api_resources/types/thread_type.py
Labels: auto:bug, size:M

#116 1.2.4
  portkey_ai/version.py
Labels: auto:documentation, size:XS
