Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-01, with the labels that each got.

#62 Rename prompt to prompts.
  portkey_ai/__init__.py
  portkey_ai/api_resources/__init__.py
  portkey_ai/api_resources/apis/__init__.py
  portkey_ai/api_resources/apis/generation.py
  portkey_ai/api_resources/client.py
  portkey_ai/version.py
Labels: auto:bug, size:S

#63 Move pydantic from equals to gt version number
  portkey_ai/version.py
  setup.cfg
Labels: auto:improvement, size:XS

#68 chore: update typing extensions version constraint
  setup.cfg
Labels: lgtm, auto:improvement, size:XS

#69 feat: bump version for release
  portkey_ai/version.py
Labels: lgtm, auto:enhancement, size:XS

#70 feat: update classes with latest openai signature
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:M

#72 feat: release 1.1.3
  portkey_ai/version.py
Labels: lgtm, auto:enhancement, size:XS

#74 fix: add default value in optional field for pydantic v2 compatibility
  portkey_ai/api_resources/utils.py
Labels: lgtm, auto:bug, size:XS

#75 Bump version to 1.1.4
  portkey_ai/version.py
Labels: auto:improvement, size:XS

#77 Relax `mypy` version constraint
  setup.cfg
Labels: lgtm, auto:improvement, size:XS

#78 feat: bump version to 1.1.5
  portkey_ai/version.py
Labels: size:XS
