Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-05, with the labels that each got.

#133 Feat/openai1.26.0
  portkey_ai/__init__.py
  portkey_ai/api_resources/__init__.py
  portkey_ai/api_resources/apis/__init__.py
  portkey_ai/api_resources/apis/assistants.py
  portkey_ai/api_resources/apis/audio.py
  portkey_ai/api_resources/apis/batches.py
  portkey_ai/api_resources/apis/chat_complete.py
  portkey_ai/api_resources/apis/complete.py
  portkey_ai/api_resources/apis/fine_tuning.py
  portkey_ai/api_resources/apis/main_files.py
  portkey_ai/api_resources/apis/moderations.py
  portkey_ai/api_resources/apis/threads.py
  portkey_ai/api_resources/apis/vector_stores.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/types/assistant_type.py
  portkey_ai/api_resources/types/audio_types.py
  portkey_ai/api_resources/types/batches_type.py
  portkey_ai/api_resources/types/fine_tuning_type.py
  portkey_ai/api_resources/types/moderations_type.py
  portkey_ai/api_resources/types/thread_message_type.py
  portkey_ai/api_resources/types/vector_stores_type.py
  tests/configs/audio/single_provider/single_provider.json
  tests/configs/audio/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/audio/single_with_basic_config/single_with_basic_config.json
  tests/configs/audio/speech.mp3
  tests/configs/moderations/single_provider/single_provider.json
  tests/configs/moderations/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/moderations/single_with_basic_config/single_with_basic_config.json
  tests/models.json
  tests/test_assistants.py
  tests/test_async_audio_speech.py
  tests/test_async_audio_transcript.py
  tests/test_async_audio_translation.py
  tests/test_async_moderations.py
  tests/test_audio_speech.py
  tests/test_audio_transcript.py
  tests/test_audio_translation.py
  tests/test_moderations.py
Labels: auto:enhancement, size:XXL

#118 update feedback
  portkey_ai/api_resources/apis/api_resource.py
  portkey_ai/api_resources/apis/feedback.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/types/feedback_type.py
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:L

#130 Hotfix/metadata
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
Labels: lgtm, size:S

#132 feat: added support for cache_namespace header
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:S

#135 Feat/headers proj org
  portkey_ai/api_resources/apis/create_headers.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:L

#138 hotfix: response type for prompt completions
  portkey_ai/api_resources/types/generation_type.py
Labels: auto:bug, size:S

#140 fix: linting issues
  portkey_ai/api_resources/apis/api_resource.py
  portkey_ai/api_resources/apis/create_headers.py
  portkey_ai/api_resources/apis/feedback.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/types/feedback_type.py
  portkey_ai/api_resources/utils.py
Labels: auto:refactor, size:M

#141 1.3.0
  portkey_ai/version.py
Labels: size:XS

#142 Sanity Check
  portkey_ai/api_resources/apis/create_headers.py
Labels: auto:nit, size:XS

#143 1.3.1
  portkey_ai/version.py
Labels: auto:enhancement, size:XS
