Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-08, with the labels that each got.

#197 Traces
  portkey_ai/api_resources/apis/logger.py
  portkey_ai/llms/langchain/portkey_langchain_callback.py
  portkey_ai/llms/llama_index/portkey_llama_callback.py
Labels: auto:enhancement, size:XXL

#200 None Type LlamaIndex payload
  portkey_ai/langchain/__init__.py
  portkey_ai/langchain/portkey_langchain_callback_handler.py
  portkey_ai/llamaindex/__init__.py
  portkey_ai/llamaindex/portkey_llama_callback_handler.py
  portkey_ai/llms/langchain/__init__.py
  portkey_ai/llms/llama_index/__init__.py
  tests/test_llm_langchain.py
  tests/test_llm_llamaindex.py
Labels: lgtm, auto:bug, size:M

#201 1.8.1
  portkey_ai/version.py
Labels: size:XS

#180 Accepting files in post method
  portkey_ai/api_resources/apis/post.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/utils.py
Labels: auto:enhancement, size:M

#202 1.8.2
  portkey_ai/version.py
Labels: size:XS

#204 Langchain Events
  portkey_ai/langchain/portkey_langchain_callback_handler.py
Labels: lgtm, auto:improvement, size:L

#207 Feat/langchain payload
  portkey_ai/langchain/portkey_langchain_callback_handler.py
Labels: auto:enhancement, size:M

#208 1.8.4
  portkey_ai/version.py
Labels: size:XS

#211 Llama payload
  portkey_ai/llamaindex/portkey_llama_callback_handler.py
Labels: auto:refactor, size:L

#212 1.8.5
  portkey_ai/version.py
Labels: auto:improvement, size:XS

#209 fix: Add huggingface_base_url parameter to support autocompletions for x-portkey-huggingface-base-url header
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/utils.py
Labels: lgtm, size:S

#214 Stream for Audio Speech
  portkey_ai/api_resources/apis/audio.py
Labels: size:XS

#215 1.8.6
  portkey_ai/version.py
Labels: lgtm, size:XS
