Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-11, with the labels that each got.

#236 feat: logs-exports api
  portkey_ai/__init__.py
  portkey_ai/api_resources/__init__.py
  portkey_ai/api_resources/apis/__init__.py
  portkey_ai/api_resources/apis/logs.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/types/logs_type.py
  portkey_ai/api_resources/utils.py
Labels: lgtm, auto:enhancement, size:L

#240 Remove `mypy` from dependencies
  setup.cfg
Labels: lgtm, size:XS

#241 1.9.4
  portkey_ai/version.py
Labels: lgtm, size:XS

#231 BaseURL and APIKey Optional
  portkey_ai/_vendor/openai/_exceptions.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/global_constants.py
  portkey_ai/api_resources/utils.py
Labels: lgtm, auto:enhancement, size:M

#242 fix: remove duplicate dependencies in `extras_require`
  setup.cfg
Labels: lgtm, size:XS

#244 feat: stream for threads and runs
  portkey_ai/api_resources/apis/threads.py
Labels: lgtm, auto:enhancement, size:L

#246 1.9.6
  portkey_ai/version.py
Labels: lgtm, size:XS

#251 1.9.7
  portkey_ai/version.py
Labels: lgtm, size:XS
