Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2024-02, with the labels that each got.

#80 feat: allow new embeddings params like dimensions
  portkey_ai/api_resources/apis/embeddings.py
Labels: auto:enhancement, size:S

#81 feat: bump version to 1.1.6
  portkey_ai/version.py
Labels: auto:enhancement, size:XS

#85 Feat/async
  portkey_ai/__init__.py
  portkey_ai/api_resources/__init__.py
  portkey_ai/api_resources/apis/__init__.py
  portkey_ai/api_resources/apis/api_resource.py
  portkey_ai/api_resources/apis/chat_complete.py
  portkey_ai/api_resources/apis/complete.py
  portkey_ai/api_resources/apis/embeddings.py
  portkey_ai/api_resources/apis/feedback.py
  portkey_ai/api_resources/apis/generation.py
  portkey_ai/api_resources/apis/post.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/common_types.py
  portkey_ai/api_resources/streaming.py
  setup.cfg
  tests/configs/chat_completions/loadbalance_and_fallback/anthropic_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/anyscale_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/azure_n_openai.json
  tests/configs/chat_completions/loadbalance_and_fallback/cohere_n_openai.json
  tests/configs/chat_completions/loadbalance_with_two_apikeys/loadbalance_with_two_apikeys.json
  tests/configs/chat_completions/single_provider/single_provider.json
  tests/configs/chat_completions/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/chat_completions/single_with_basic_config/single_with_basic_config.json
  tests/configs/completions/loadbalance_and_fallback/anthropic_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/anyscale_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/azure_n_openai.json
  tests/configs/completions/loadbalance_and_fallback/cohere_n_openai.json
  tests/configs/completions/loadbalance_with_two_apikeys/loadbalance_with_two_apikeys.json
  tests/configs/completions/single_provider/single_provider.json
  tests/configs/completions/single_provider_with_vk_retry_cache/single_provider_with_vk_retry_cache.json
  tests/configs/completions/single_with_basic_config/single_with_basic_config.json
  tests/models.json
  tests/test_async_chat_complete.py
  tests/test_async_complete.py
Labels: lgtm, auto:enhancement, size:XXL

#86 feat: release-1.1.7
  portkey_ai/version.py
Labels: auto:enhancement, size:XS
