Repository Portkey-AI/portkey-python-sdk, pull requests merged in 2025-02, with the labels that each got.

#282 instrumentation using monkey patching and open telemetry
  Makefile
  portkey_ai/api_resources/apis/logger.py
  portkey_ai/api_resources/base_client.py
  portkey_ai/api_resources/client.py
  portkey_ai/api_resources/instrumentation/__init__.py
  portkey_ai/api_resources/instrumentation/crewai/__init__.py
  portkey_ai/api_resources/instrumentation/crewai/instrumentation.py
  portkey_ai/api_resources/instrumentation/crewai/patch.py
  portkey_ai/api_resources/instrumentation/langgraph/__init__.py
  portkey_ai/api_resources/instrumentation/langgraph/instrumentation.py
  portkey_ai/api_resources/instrumentation/langgraph/patch.py
  portkey_ai/api_resources/instrumentation/litellm/__init__.py
  portkey_ai/api_resources/instrumentation/litellm/instrumentation.py
  portkey_ai/api_resources/instrumentation/litellm/patch.py
  portkey_ai/api_resources/instrumentation/openai/__init__.py
  portkey_ai/api_resources/instrumentation/openai/instrumentation.py
  portkey_ai/api_resources/instrumentation/openai/patch.py
  portkey_ai/api_resources/instrumentation/portkey_span_exporter.py
  portkey_ai/api_resources/instrumentation/utils.py
  portkey_ai/api_resources/utils.py
  portkey_ai/utils/__init__.py
  portkey_ai/utils/hashing_utils.py
  portkey_ai/utils/json_utils.py
  setup.cfg
Labels: lgtm, auto:enhancement, size:XL

#289 Import Error Message
  portkey_ai/api_resources/client.py
Labels: lgtm, auto:bug, size:XS

#290 Import error message
  portkey_ai/api_resources/client.py
Labels: lgtm, auto:bug, size:XS

#291 1.10.3
  portkey_ai/version.py
Labels: lgtm, size:XS

#295 fix: list type for content
  portkey_ai/api_resources/types/chat_complete_type.py
Labels: lgtm, size:XS

#296 1.10.4
  portkey_ai/version.py
Labels: lgtm, size:XS

#298 feat: support for batches output
  portkey_ai/api_resources/apis/batches.py
Labels: lgtm, auto:enhancement, size:M

#299 1.10.5
  portkey_ai/version.py
Labels: lgtm, size:XS

#301 Retry for timeout
  portkey_ai/_vendor/openai/_base_client.py
Labels: lgtm, auto:bug, size:XS

#302 Fix "Retry for timeout"
  portkey_ai/_vendor/openai/_base_client.py
Labels: lgtm, size:XS

#303 1.11.0
  portkey_ai/version.py
Labels: lgtm, size:XS
